import type { AssetDefinition } from './types'

export const builtInAssets: AssetDefinition[] = [
  {
    id: 'person-whitebox',
    label: 'Person',
    category: 'character',
    kind: 'primitive',
    prefab: 'person',
    dimensions: [0.7, 1.8, 0.7],
  },
  {
    id: 'block-building',
    label: 'Building',
    category: 'building',
    kind: 'primitive',
    prefab: 'block-building',
    dimensions: [3, 3.2, 2.2],
  },
  {
    id: 'tower-building',
    label: 'Tower',
    category: 'building',
    kind: 'primitive',
    prefab: 'tower',
    dimensions: [1.6, 5, 1.6],
  },
  {
    id: 'lowpoly-tree',
    label: 'Tree',
    category: 'plant',
    kind: 'primitive',
    prefab: 'tree',
    dimensions: [1.2, 2.6, 1.2],
  },
  {
    id: 'prop-crate',
    label: 'Crate',
    category: 'prop',
    kind: 'primitive',
    prefab: 'crate',
    dimensions: [1, 1, 1],
  },
  {
    id: 'prop-wall',
    label: 'Wall',
    category: 'prop',
    kind: 'primitive',
    prefab: 'wall',
    dimensions: [3, 1.6, 0.2],
  },
  {
    id: 'greenscreen-panel',
    label: 'Green Screen',
    category: 'prop',
    kind: 'primitive',
    prefab: 'greenscreen',
    dimensions: [4, 2.25, 0.08],
  },
  {
    id: 'vehicle-car',
    label: 'Car',
    category: 'vehicle',
    kind: 'primitive',
    prefab: 'car',
    dimensions: [1.8, 0.9, 3.4],
  },
  {
    id: 'vehicle-truck',
    label: 'Truck',
    category: 'vehicle',
    kind: 'primitive',
    prefab: 'truck',
    dimensions: [2.1, 1.4, 4.6],
  },
  {
    id: 'vehicle-motorcycle',
    label: 'Motorcycle',
    category: 'vehicle',
    kind: 'primitive',
    prefab: 'motorcycle',
    dimensions: [0.7, 1, 2],
  },
  {
    id: 'vehicle-boat',
    label: 'Boat',
    category: 'vehicle',
    kind: 'primitive',
    prefab: 'boat',
    dimensions: [1.5, 0.7, 3.2],
  },
  {
    id: 'aircraft-airplane',
    label: 'Airplane',
    category: 'aircraft',
    kind: 'primitive',
    prefab: 'airplane',
    dimensions: [3.6, 0.8, 3.2],
  },
  {
    id: 'aircraft-drone',
    label: 'Drone',
    category: 'aircraft',
    kind: 'primitive',
    prefab: 'drone',
    dimensions: [1.7, 0.35, 1.7],
  },
  {
    id: 'aircraft-helicopter',
    label: 'Helicopter',
    category: 'aircraft',
    kind: 'primitive',
    prefab: 'helicopter',
    dimensions: [2.3, 1, 3.5],
  },
]

export const assetCategoryLabels: Record<AssetDefinition['category'], string> = {
  character: 'Characters',
  building: 'Buildings',
  plant: 'Plants',
  prop: 'Props',
  vehicle: 'Vehicles',
  aircraft: 'Aircraft',
  camera: 'Cameras',
}

export const getAssetById = (
  assets: AssetDefinition[],
  assetId: string,
): AssetDefinition | undefined => assets.find((asset) => asset.id === assetId)
